### ISSUE TITLE
Deployment of 6.5.2 tag on dockerhub ?

### ISSUE THREAD

**Issue by Tibo75** [varnish/docker-varnish#38]
Hi,

is there any plan to create a 6.5.2 docker version of varnish image in dockerhub ?

In my case, the 6.5.2 version were deployed in some environments (out of docker) but we would like to keep our dev environment (using docker) in accordance to this specific version.

Thanks in advance to let us know if this is planned or not.

If requested, I could send a PR in order to propose this (potentially with some guidance on your versioning).

Regards,

**Comment by gquintard** [comment]
Hi,

There's no plan for this at the moment, we only track the latest series and the current LTS, so 6.5 is out of scope. In this particular case, the next Varnish release is due next week, meaning 6.5 will be EOL very soon.

To avoid this in the future, you can create a create a PR so we can track the `less-than-fresh` version in addition `fresh` and `stable`. It should be as simple as adding a new set of directories and creating an entry in https://github.com/varnish/docker-varnish/blob/master/populate.sh#L6

Otherwise, you can also easily create your own local image by updating `populate.sh`, regenerating the `Dockerfiles` and building them

**Comment by Tibo75** [comment]
Thanks, I will have a look at both options.

Regarding EOL very soon reached.. would that mean the date provided in [this page](https://varnish-cache.org/releases/) would be 
202**1**-09-15 instead of  2022-09-15  ?

Regardless of this important information and while I'm having a look at what the PR would be, where should I point to regarding the [PKG_COMMIT](https://github.com/varnish/docker-varnish/blob/master/populate.sh#L19) in [this repository](https://github.com/varnishcache/pkg-varnish-cache) in order to get the 6.5.2 version ? 
I can't see any specific tag for 6.5.2

Thanks in advance!

**Comment by gquintard** [comment]
> Regarding EOL very soon reached.. would that mean the date provided in this page would be
2021-09-15 instead of 2022-09-15 ?

Let me check, the project usually only provides support for only one year after release, so that 2022 feels weird, but I may have missed a memo.

> Regardless of this important information and while I'm having a look at what the PR would be, where should I point to regarding the PKG_COMMIT in this repository in order to get the 6.5.2 version ?
I can't see any specific tag for 6.5.2

Indeed, we don't have tags here, just pick the tip of `6.5`(currently 6890e35e3fd95fe2db068f8899dfff0855c354be)

**Comment by gquintard** [comment]
hello again, I check, and indeed, the dates are currently wrong on the website. I'll close this for now, but I will be happy to lend a hand it you decide to open a PR to support the N-1 release on `docker`

**Comment by gquintard** [comment]
`7.0.0` is out, and because of this ticket, I kept `6.6` around to mirror the upstream support window, so no PR needed
