### ISSUE TITLE
Why do we need wrapper scripts?

### ISSUE THREAD

**Issue by Dridi** [varnish/docker-varnish#39]
What is the purpose of this?

https://github.com/varnish/docker-varnish/blob/083e40e2096a7caff2551b6d055571d64ca16b14/scripts/varnishd#L1-L5

Today I needed to grab a shell into a varnish container and couldn't wreck havoc^W^W inspect it without this script and its symlinks getting in the way. In particular, the unconditional `-n` option becomes a problem once you try using a `varnishlog` or something else option that is incompatible with it.

The workaround was not to rely on the `$PATH` and run `/usr/bin/varnishlog` in the Debian container but I'm really wondering about the relevance of a script that inserts itself in the call chain only to force a `-n` option.

My guess, you want to avoid involving the host name in the Varnish working directory.

**Comment by gquintard** [comment]
The short of it: so that people don't have issues while running `docker-compose`. I this case, each container has its own host so the workdir had to be manually specified which was a inconvenient. You can check the closed issues for more context, but that's the gist of it.

I would welcome a cleaner solution, if for example we could specify a default `-n` at compile time.

**Comment by gquintard** [comment]
with `7.0`, the default workdir doesn't involve the machine's hostname, so the wrapper scripts aren't needed anymore.

closed with https://github.com/varnish/docker-varnish/commit/b4396ad550ffa073bf1e3ceff4ae0ebfcd7023bb and https://github.com/docker-library/official-images/pull/10927
