### ISSUE TITLE
Alpine based image of Varnish 6.0 Lts is missing 

### ISSUE THREAD

**Issue by ihor-sviziev** [varnish/docker-varnish#57]
Is there any reason why varnish 6.0 (lts) isn’t available as alpine based image?

**Comment by navarr** [comment]
There isn't a version available upstream: https://hub.docker.com/_/varnish

We'd have to try to build Varnish 6.0 on Alpine and as of right now, I don't think theres any value in that.

**Comment by gquintard** [comment]
Hi!

Mostly, because I didn't wish to spend the time backporting the changes. If you look at `stable/debian/Dockerfile`, you'll see that originally we use pre-buit packages instead of compiling from source, and there were no `alpine` packages compiled by the Varnish project.
Also, be aware that 6.0 uses `libexecinfo` instead of `libunwind`, and it's majorly broken in `alpine`, leading to failing tests.

That being said, if you want to offer a PR, I'll gladly look at it
